services:
  - type: web
    name: sirus-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests -T 1C
    startCommand: java -Xms512m -Xmx1g -XX:+UseG1GC -XX:+UseStringDeduplication -jar target/sirus-backend-0.0.1-SNAPSHOT.jar
    healthCheckPath: /api/test/health
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres
      - key: DATABASE_USERNAME
        value: postgres.wynfrojhkzddzjbrpdcr
      - key: DATABASE_PASSWORD
        value: a*Xxk3B7?HF8&3r
      - key: JWT_SECRET
        value: oieoknjsemblboenejfkf681616fdsfdsfscvxv
      - key: JWT_EXPIRATION
        value: 86400000
      - key: ADMIN_PASSWORD
        value: moja-admin-lozinka123!!_
      - key: SECURITY_HEADERS_ENABLED
        value: true
      - key: EUK_ALLOWED_DOMAINS
        value: https://euk.vercel.app,https://euk-it-sectors-projects.vercel.app,https://sirus-fullstack.onrender.com
      - key: EUK_RATE_LIMIT_ENABLED
        value: true
      - key: EUK_RATE_LIMIT_MAX_REQUESTS
        value: 150
      - key: JAVA_OPTS
        value: "-Xms512m -Xmx1g -XX:+UseG1GC"
      - key: MAVEN_OPTS
        value: "-Xmx512m" 